version: '3.4'

services:

  # cluster peer2
  # use peer0 as the bootstrap peer

  ipfs2:
    container_name: ipfs2
    image: ipfs/go-ipfs:release
    volumes:
      - /private/var/services/librum/ipfs/ipfs2:/data/ipfs

  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - /private/var/services/librum/ipfs/cluster2:/data/ipfs-cluster
    command:
      - "daemon --bootstrap ${CLUSTER_PEER0}" # add multiple peers with comma seperated
